### ISSUE TITLE
028_gradle

### ISSUE THREAD

**Issue by nobuakiSuzuki** [kl-labo/young#28]
gradleを亀野さんのPGPracticeで初めて使ったが、Mavenとは結構違うなと感じたので、
自分なりに調べてまとめてみようと思います。

**Comment by murayama333** [comment]
いいすね。がんばって。

**Comment by nobuakiSuzuki** [comment]
さっそくのレスポンスありがとうございます。
頑張ります。

**Comment by murayama333** [comment]
プルリクもらってマージしたのでクローズしましたー。
